version: '3.7'

services:

    mongodb:
        image: mongo:3.6.18
        container_name: mongo-3.6.18
        volumes:
            - ./services/mongodb/data:/data/db
        environment:
            - MONGO_DB_ROOT_USERNAME=main
            - MONGO_DB_ROOT_PASSWORD=main
        ports:
            - '27017:27017'

    rabbitmq:
        image: rabbitmq:3.8-management
        container_name: rabbitmq-3.8.3
        volumes:
            - ./services/rabbitmq/data:/var/lib/rabbitmq/
            - ./services/rabbitmq/logs:/var/log/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=main
            - RABBITMQ_DEFAULT_PASS=main
        ports:
            - '5672:5672'
            - '15672:15672'

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            discovery.type: "single-node"
            ES_JAVA_OPTS: "-Xms2g -Xmx2g"
        volumes:
            - ./services/elasticsearch:/usr/share/elasticsearch/data
